kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2       # Stable and compatible with many tools
  - role: control-plane
    image: kindest/node:v1.29.2
  - role: control-plane
    image: kindest/node:v1.29.2
  # - role: worker
  #   image: kindest/node:v1.29.2

networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443

