apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-storage
  labels:
    app: object-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-storage
  template:
    metadata:
      labels:
        app: object-storage
    spec:
      serviceAccountName: cloud-controller
      containers:
      - name: object-storage
        image: psethi/object-storage:{{ include "helper.imageTag" . }}
        env:
        - name: MONGO_CONFIGDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: configdb-user
              key: username
        - name: MONGO_CONFIGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: configdb-user
              key: password
        volumeMounts:
        - name: config-vol
          mountPath: /opt/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-vol
        configMap:
          name: object-storage-config
          defaultMode: 0555
