apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
type: kubernetes.io/tls
data:
{{ (.Files.Glob "files/tls.crt").AsSecrets | indent 2 }}
{{ (.Files.Glob "files/tls.key").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
data:
  username: {{ .Values.keycloak.credentials.username | b64enc }}
  password: {{ .Values.keycloak.credentials.password | b64enc }}
