apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-ui-config
data:
  default.conf: |
    server {
        listen       443 ssl;
        listen  [::]:443 ssl;
        server_name  _;
    
        ssl_certificate /opt/certs/tls.crt;
        ssl_certificate_key /opt/certs/tls.key;
    
        location /apidocs/ {
          proxy_pass         "http://auth:8080";
        }

        location /api/ {
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   Host $http_host:$server_port;
            proxy_pass         "http://auth:8080";
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        #error_page  404              /404.html;
    
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
