apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ui
  labels:
    app: cloud-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ui
  template:
    metadata:
      labels:
        app: cloud-ui
    spec:
      containers:
      - name: cloud-ui
        image: psethi/cloud-ui:{{ include "helper.imageTag" . }}
        volumeMounts:
        - name: default-conf-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: default-conf-vol
        configMap:
          name: cloud-ui-config
          defaultMode: 0555
