{{- $secretName := printf "%s-config" .Chart.Name }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $random := "" }}
{{- if $existing }}
  {{- $random = index $existing.data "mongod_key" }}
{{- else }}
  {{- $random = randBytes 756 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  mongod_key: {{ $random }}
{{ (.Files.Glob "files/mongod.conf").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-user
type: Opaque
stringData:
  username: admin
  password: password
