apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
