apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
      spread: spread-across
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: psethi/auth-gateway:{{ include "helper.imageTag" . }}
        env:
        - name: MONGO_CONFIGDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: configdb-user
              key: username
        - name: MONGO_CONFIGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: configdb-user
              key: password
        volumeMounts:
        - name: config-vol
          mountPath: /opt/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-vol
        configMap:
          name: auth-config
          defaultMode: 0555
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            spread: spread-across
